# Generated by Django 5.1.4 on 2025-01-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(default='https://i.imgur.com/lHubf1C.jpeg', max_length=600),
        ),
    ]
