# Generated by Django 5.1.4 on 2025-01-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steam_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
